<?php

$this->Titles['MrMen'] = array(
   'Tickle' => array('title' => "Mr. Tickle", 'type' => "Amazon", 'id' => "1405235616", 'image' => "Images/Tickle.jpg"),
   'Greedy' => array('title' => "Mr. Greedy", 'type' => "Amazon", 'id' => "1405235535", 'image' => "Images/Greedy.jpg"),
   'Happy' => array('title' => "Mr. Happy", 'description' => "Type: Book<br>Price: &pound;2.50", 'type' => "Amazon", 'id' => "1405235519", 'image' => "Images/Happy.jpg"),
   'Nosey' => array('title' => "Mr. Nosey", 'type' => "Amazon", 'id' => "1405235756", 'image' => "Images/Nosey.jpg"),
   'Sneeze' => array('title' => "Mr. Sneeze", 'type' => "Amazon", 'id' => "1405235594", 'image' => "Images/Sneeze.jpg" ),
   'Bump' => array('title' => "Mr. Bump", 'type' => "Amazon", 'id' => "1405235578", 'image' => "Images/Bump.jpg" ),
   'Snow' => array('title' => "Mr. Snow", 'type' => "Amazon", 'id' => "1405235713", 'image' => "Images/Snow.jpg" ),
   'Messy' => array('title' => "Mr. Messy", 'type' => "Amazon", 'id' => "1405235640", 'image' => "Images/Messy.jpg" ),
   'Topsy-Turvy' => array('title' => "Mr. Topsy-Turvy", 'type' => "Amazon", 'id' => "1405235861", 'image' => "Images/Topsy-Turvy.jpg" ),
   'Silly' => array('title' => "Mr. Silly", 'type' => "Amazon", 'id' => "1405235845", 'image' => "Images/Silly.jpg" ),
   'Uppity' => array('title' => "Mr. Uppity", 'type' => "Amazon", 'id' => "1405235950", 'image' => "Images/Uppity.jpg" ),
   'Small' => array('title' => "Mr. Small", 'type' => "Amazon", 'id' => "1405235632", 'image' => "Images/Small.jpg" ),
   'Daydream' => array('title' => "Mr. Daydream", 'type' => "Amazon", 'id' => "1405235772", 'image' => "Images/Daydream.jpg" ),
   'Forgetful' => array('title' => "Mr. Forgetful", 'type' => "Amazon", 'id' => "1405235764", 'image' => "Images/Forgetful.jpg" ),
   'Jelly' => array('title' => "Mr. Jelly", 'type' => "Amazon", 'id' => "1405235667", 'image' => "Images/Jelly.jpg" ),
   'Noisy' => array('title' => "Mr. Noisy", 'type' => "Amazon", 'id' => "1405235683", 'image' => "Images/Noisy.jpg" ),
   'Good' => array('title' => "Mr. Good", 'type' => "Amazon", 'id' => "1405235675", 'image' => "Images/Good.jpg" ),
   'Brave' => array('title' => "Mr. Brave", 'type' => "Amazon", 'id' => "1405235608", 'image' => "Images/Brave.jpg" ),
   'Cheerful' => array('title' => "Mr. Cheerful", 'type' => "Amazon", 'id' => "1405235500", 'image' => "Images/Cheerful.jpg" ),
   'Cool' => array('title' => "Mr. Cool", 'type' => "Amazon", 'id' => "1405235551", 'image' => "Images/Cool.jpg" ),
   'Strong' => array('title' => "Mr. Strong", 'type' => "Amazon", 'id' => "1405235721", 'image' => "Images/Strong.jpg" ),
   'Wrong' => array('title' => "Mr. Wrong", 'type' => "Amazon", 'id' => "140523590X", 'image' => "Images/Wrong.jpg" ),
   'Lazy' => array('title' => "Mr. Lazy", 'type' => "Amazon", 'id' => "1405235748", 'image' => "Images/Lazy.jpg" ),
   'Tall' => array('title' => "Mr. Tall", 'type' => "Amazon", 'id' => "1405235586", 'image' => "Images/Tall.jpg" ),
   'Mean' => array('title' => "Mr. Mean", 'type' => "Amazon", 'id' => "1405235624", 'image' => "Images/Mean.jpg" ),
   'Impossible' => array('title' => "Mr. Impossible", 'type' => "Amazon", 'id' => "1405235799", 'image' => "Images/Impossible.jpg" ),
   'Fussy' => array('title' => "Mr. Fussy", 'type' => "Amazon", 'id' => "140523587X", 'image' => "Images/Fussy.jpg" ),
   'Rude' => array('title' => "Mr. Rude", 'type' => "Amazon", 'id' => "1405235659", 'image' => "Images/Rude.jpg" ),
   'Chatterbox' => array('title' => "Mr. Chatterbox", 'type' => "Amazon", 'id' => "1405235802", 'image' => "Images/Chatterbox.jpg" ),
   'Funny' => array('title' => "Mr. Funny", 'type' => "Amazon", 'id' => "1405235705", 'image' => "Images/Funny.jpg" ),
   'Worry' => array('title' => "Mr. Worry", 'type' => "Amazon", 'id' => "1405235896", 'image' => "Images/Worry.jpg" ),
   'Grumpy' => array('title' => "Mr. Grumpy", 'type' => "Amazon", 'id' => "1405235837", 'image' => "Images/Grumpy.jpg" ),
   'Bounce' => array('title' => "Mr. Bounce", 'type' => "Amazon", 'id' => "1405235918", 'image' => "Images/Bounce.jpg" ),
   'Perfect' => array('title' => "Mr. Perfect", 'type' => "Amazon", 'id' => "1405235926", 'image' => "Images/Perfect.jpg" ),
   'Dizzy' => array('title' => "Mr. Dizzy", 'type' => "Amazon", 'id' => "1405235780", 'image' => "Images/Dizzy.jpg" ),
   'Busy' => array('title' => "Mr. Busy", 'type' => "Amazon", 'id' => "1405235934", 'image' => "Images/Busy.jpg" ),
   'Skinny' => array('title' => "Mr. Skinny", 'type' => "Amazon", 'id' => "1405235888", 'image' => "Images/Skinny.jpg" ),
   'Slow' => array('title' => "Mr. Slow", 'type' => "Amazon", 'id' => "140523573X", 'image' => "Images/Slow.jpg" ),
   'Quiet' => array('title' => "Mr. Quiet", 'type' => "Amazon", 'id' => "1405235527", 'image' => "Images/Quiet.jpg" ),
   'Rush' => array('title' => "Mr. Rush", 'type' => "Amazon", 'id' => "1405235942", 'image' => "Images/Rush.jpg" ),
   'Muddle' => array('title' => "Mr. Muddle", 'type' => "Amazon", 'id' => "1405235691", 'image' => "Images/Muddle.jpg" ),
   'Mischief' => array('title' => "Mr. Mischief", 'type' => "Amazon", 'id' => "1405235810", 'image' => "Images/Mischief.jpg" ),
   'Nonsense' => array('title' => "Mr. Nonsense", 'type' => "Amazon", 'id' => "1405235829", 'image' => "Images/Nonsense.jpg" ),
   'Clumsy' => array('title' => "Mr. Clumsy", 'type' => "Amazon", 'id' => "140523556X", 'image' => "Images/Clumsy.jpg" ),
   'Clever' => array('title' => "Mr. Clever", 'type' => "Amazon", 'id' => "1405235853", 'image' => "Images/Clever.jpg" ),
   'Grumble' => array('title' => "Mr. Grumble", 'type' => "Amazon", 'id' => "1405235543", 'image' => "Images/Grumble.jpg" )
);

?>